// MIT License

// Copyright (c) 2020 Yash Handa

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package icons

var iconExt = map[string]iconInfo{
	"htm":               iconSet["html"],
	"html":              iconSet["html"],
	"xhtml":             iconSet["html"],
	"html_vm":           iconSet["html"],
	"asp":               iconSet["html"],
	"jade":              iconSet["pug"],
	"pug":               iconSet["pug"],
	"md":                iconSet["markdown"],
	"markdown":          iconSet["markdown"],
	"rst":               iconSet["markdown"],
	"blink":             iconSet["blink"],
	"css":               iconSet["css"],
	"scss":              iconSet["sass"],
	"sass":              iconSet["sass"],
	"less":              iconSet["less"],
	"json":              iconSet["json"],
	"tsbuildinfo":       iconSet["json"],
	"json5":             iconSet["json"],
	"jsonl":             iconSet["json"],
	"ndjson":            iconSet["json"],
	"jinja":             iconSet["jinja"],
	"jinja2":            iconSet["jinja"],
	"j2":                iconSet["jinja"],
	"jinja-html":        iconSet["jinja"],
	"sublime-project":   iconSet["sublime"],
	"sublime-workspace": iconSet["sublime"],
	"yaml":              iconSet["yaml"],
	"yaml-tmlanguage":   iconSet["yaml"],
	"yml":               iconSet["yaml"],
	"xml":               iconSet["xml"],
	"plist":             iconSet["xml"],
	"xsd":               iconSet["xml"],
	"dtd":               iconSet["xml"],
	"xsl":               iconSet["xml"],
	"xslt":              iconSet["xml"],
	"resx":              iconSet["xml"],
	"iml":               iconSet["xml"],
	"xquery":            iconSet["xml"],
	"tmLanguage":        iconSet["xml"],
	"manifest":          iconSet["xml"],
	"project":           iconSet["xml"],
	"png":               iconSet["image"],
	"jpeg":              iconSet["image"],
	"jpg":               iconSet["image"],
	"gif":               iconSet["image"],
	"ico":               iconSet["image"],
	"tif":               iconSet["image"],
	"tiff":              iconSet["image"],
	"psd":               iconSet["image"],
	"psb":               iconSet["image"],
	"ami":               iconSet["image"],
	"apx":               iconSet["image"],
	"bmp":               iconSet["image"],
	"bpg":               iconSet["image"],
	"brk":               iconSet["image"],
	"cur":               iconSet["image"],
	"dds":               iconSet["image"],
	"dng":               iconSet["image"],
	"exr":               iconSet["image"],
	"fpx":               iconSet["image"],
	"gbr":               iconSet["image"],
	"img":               iconSet["image"],
	"jbig2":             iconSet["image"],
	"jb2":               iconSet["image"],
	"jng":               iconSet["image"],
	"jxr":               iconSet["image"],
	"pbm":               iconSet["image"],
	"pgf":               iconSet["image"],
	"pic":               iconSet["image"],
	"raw":               iconSet["image"],
	"webp":              iconSet["image"],
	"eps":               iconSet["image"],
	"afphoto":           iconSet["image"],
	"ase":               iconSet["image"],
	"aseprite":          iconSet["image"],
	"clip":              iconSet["image"],
	"cpt":               iconSet["image"],
	"heif":              iconSet["image"],
	"heic":              iconSet["image"],
	"kra":               iconSet["image"],
	"mdp":               iconSet["image"],
	"ora":               iconSet["image"],
	"pdn":               iconSet["image"],
	"reb":               iconSet["image"],
	"sai":               iconSet["image"],
	"tga":               iconSet["image"],
	"xcf":               iconSet["image"],
	"js":                iconSet["javascript"],
	"esx":               iconSet["javascript"],
	"mj":                iconSet["javascript"],
	"jsx":               iconSet["react"],
	"tsx":               iconSet["react_ts"],
	"ini":               iconSet["settings"],
	"dlc":               iconSet["settings"],
	"dll":               iconSet["settings"],
	"config":            iconSet["settings"],
	"conf":              iconSet["settings"],
	"properties":        iconSet["settings"],
	"prop":              iconSet["settings"],
	"settings":          iconSet["settings"],
	"option":            iconSet["settings"],
	"props":             iconSet["settings"],
	"toml":              iconSet["settings"],
	"prefs":             iconSet["settings"],
	"dotsettings":       iconSet["settings"],
	"cfg":               iconSet["settings"],
	"ts":                iconSet["typescript"],
	"marko":             iconSet["markojs"],
	"pdf":               iconSet["pdf"],
	"xlsx":              iconSet["table"],
	"xls":               iconSet["table"],
	"csv":               iconSet["table"],
	"tsv":               iconSet["table"],
	"vscodeignore":      iconSet["vscode"],
	"vsixmanifest":      iconSet["vscode"],
	"vsix":              iconSet["vscode"],
	"code-workplace":    iconSet["vscode"],
	"csproj":            iconSet["visualstudio"],
	"ruleset":           iconSet["visualstudio"],
	"sln":               iconSet["visualstudio"],
	"suo":               iconSet["visualstudio"],
	"vb":                iconSet["visualstudio"],
	"vbs":               iconSet["visualstudio"],
	"vcxitems":          iconSet["visualstudio"],
	"vcxproj":           iconSet["visualstudio"],
	"pdb":               iconSet["database"],
	"sql":               iconSet["mysql"],
	"pks":               iconSet["database"],
	"pkb":               iconSet["database"],
	"accdb":             iconSet["database"],
	"mdb":               iconSet["database"],
	"db":                iconSet["database"],
	"sqlite":            iconSet["sqlite"],
	"sqlite3":           iconSet["sqlite"],
	"pgsql":             iconSet["postgresql"],
	"postgres":          iconSet["postgresql"],
	"psql":              iconSet["postgresql"],
	"cs":                iconSet["csharp"],
	"csx":               iconSet["csharp"],
	"qs":                iconSet["qsharp"],
	"zip":               iconSet["zip"],
	"tar":               iconSet["zip"],
	"gz":                iconSet["zip"],
	"xz":                iconSet["zip"],
	"br":                iconSet["zip"],
	"bzip2":             iconSet["zip"],
	"gzip":              iconSet["zip"],
	"brotli":            iconSet["zip"],
	"7z":                iconSet["zip"],
	"rar":               iconSet["zip"],
	"tgz":               iconSet["zip"],
	"vala":              iconSet["vala"],
	"zig":               iconSet["zig"],
	"exe":               iconSet["exe"],
	"msi":               iconSet["exe"],
	"java":              iconSet["java"],
	"jar":               iconSet["java"],
	"jsp":               iconSet["java"],
	"c":                 iconSet["c"],
	"m":                 iconSet["c"],
	"i":                 iconSet["c"],
	"mi":                iconSet["c"],
	"h":                 iconSet["h"],
	"cc":                iconSet["cpp"],
	"cpp":               iconSet["cpp"],
	"cxx":               iconSet["cpp"],
	"c++":               iconSet["cpp"],
	"cp":                iconSet["cpp"],
	"mm":                iconSet["cpp"],
	"mii":               iconSet["cpp"],
	"ii":                iconSet["cpp"],
	"hh":                iconSet["hpp"],
	"hpp":               iconSet["hpp"],
	"hxx":               iconSet["hpp"],
	"h++":               iconSet["hpp"],
	"hp":                iconSet["hpp"],
	"tcc":               iconSet["hpp"],
	"inl":               iconSet["hpp"],
	"go":                iconSet["go"],
	"py":                iconSet["python"],
	"pyc":               iconSet["python-misc"],
	"whl":               iconSet["python-misc"],
	"url":               iconSet["url"],
	"sh":                iconSet["console"],
	"ksh":               iconSet["console"],
	"csh":               iconSet["console"],
	"tcsh":              iconSet["console"],
	"zsh":               iconSet["console"],
	"bash":              iconSet["console"],
	"bat":               iconSet["console"],
	"cmd":               iconSet["console"],
	"awk":               iconSet["console"],
	"fish":              iconSet["console"],
	"ps1":               iconSet["powershell"],
	"psm1":              iconSet["powershell"],
	"psd1":              iconSet["powershell"],
	"ps1xml":            iconSet["powershell"],
	"psc1":              iconSet["powershell"],
	"pssc":              iconSet["powershell"],
	"gradle":            iconSet["gradle"],
	"doc":               iconSet["word"],
	"docx":              iconSet["word"],
	"rtf":               iconSet["word"],
	"cer":               iconSet["certificate"],
	"cert":              iconSet["certificate"],
	"crt":               iconSet["certificate"],
	"pub":               iconSet["key"],
	"key":               iconSet["key"],
	"pem":               iconSet["key"],
	"asc":               iconSet["key"],
	"gpg":               iconSet["key"],
	"woff":              iconSet["font"],
	"woff2":             iconSet["font"],
	"ttf":               iconSet["font"],
	"eot":               iconSet["font"],
	"suit":              iconSet["font"],
	"otf":               iconSet["font"],
	"bmap":              iconSet["font"],
	"fnt":               iconSet["font"],
	"odttf":             iconSet["font"],
	"ttc":               iconSet["font"],
	"font":              iconSet["font"],
	"fonts":             iconSet["font"],
	"sui":               iconSet["font"],
	"ntf":               iconSet["font"],
	"mrf":               iconSet["font"],
	"lib":               iconSet["lib"],
	"bib":               iconSet["lib"],
	"rb":                iconSet["ruby"],
	"erb":               iconSet["ruby"],
	"fs":                iconSet["fsharp"],
	"fsx":               iconSet["fsharp"],
	"fsi":               iconSet["fsharp"],
	"fsproj":            iconSet["fsharp"],
	"swift":             iconSet["swift"],
	"ino":               iconSet["arduino"],
	"dockerignore":      iconSet["docker"],
	"dockerfile":        iconSet["docker"],
	"tex":               iconSet["tex"],
	"sty":               iconSet["tex"],
	"dtx":               iconSet["tex"],
	"ltx":               iconSet["tex"],
	"pptx":              iconSet["powerpoint"],
	"ppt":               iconSet["powerpoint"],
	"pptm":              iconSet["powerpoint"],
	"potx":              iconSet["powerpoint"],
	"potm":              iconSet["powerpoint"],
	"ppsx":              iconSet["powerpoint"],
	"ppsm":              iconSet["powerpoint"],
	"pps":               iconSet["powerpoint"],
	"ppam":              iconSet["powerpoint"],
	"ppa":               iconSet["powerpoint"],
	"webm":              iconSet["video"],
	"mkv":               iconSet["video"],
	"flv":               iconSet["video"],
	"vob":               iconSet["video"],
	"ogv":               iconSet["video"],
	"ogg":               iconSet["video"],
	"gifv":              iconSet["video"],
	"avi":               iconSet["video"],
	"mov":               iconSet["video"],
	"qt":                iconSet["video"],
	"wmv":               iconSet["video"],
	"yuv":               iconSet["video"],
	"rm":                iconSet["video"],
	"rmvb":              iconSet["video"],
	"mp4":               iconSet["video"],
	"m4v":               iconSet["video"],
	"mpg":               iconSet["video"],
	"mp2":               iconSet["video"],
	"mpeg":              iconSet["video"],
	"mpe":               iconSet["video"],
	"mpv":               iconSet["video"],
	"m2v":               iconSet["video"],
	"vdi":               iconSet["virtual"],
	"vbox":              iconSet["virtual"],
	"vbox-prev":         iconSet["virtual"],
	"ics":               iconSet["email"],
	"mp3":               iconSet["audio"],
	"flac":              iconSet["audio"],
	"m4a":               iconSet["audio"],
	"wma":               iconSet["audio"],
	"aiff":              iconSet["audio"],
	"coffee":            iconSet["coffee"],
	"cson":              iconSet["coffee"],
	"iced":              iconSet["coffee"],
	"txt":               iconSet["document"],
	"graphql":           iconSet["graphql"],
	"gql":               iconSet["graphql"],
	"rs":                iconSet["rust"],
	"raml":              iconSet["raml"],
	"xaml":              iconSet["xaml"],
	"hs":                iconSet["haskell"],
	"kt":                iconSet["kotlin"],
	"kts":               iconSet["kotlin"],
	"patch":             iconSet["git"],
	"lua":               iconSet["lua"],
	"clj":               iconSet["clojure"],
	"cljs":              iconSet["clojure"],
	"cljc":              iconSet["clojure"],
	"groovy":            iconSet["groovy"],
	"r":                 iconSet["r"],
	"rmd":               iconSet["r"],
	"dart":              iconSet["dart"],
	"as":                iconSet["actionscript"],
	"mxml":              iconSet["mxml"],
	"ahk":               iconSet["autohotkey"],
	"swf":               iconSet["flash"],
	"swc":               iconSet["swc"],
	"cmake":             iconSet["cmake"],
	"asm":               iconSet["assembly"],
	"a51":               iconSet["assembly"],
	"inc":               iconSet["assembly"],
	"nasm":              iconSet["assembly"],
	"s":                 iconSet["assembly"],
	"ms":                iconSet["assembly"],
	"agc":               iconSet["assembly"],
	"ags":               iconSet["assembly"],
	"aea":               iconSet["assembly"],
	"argus":             iconSet["assembly"],
	"mitigus":           iconSet["assembly"],
	"binsource":         iconSet["assembly"],
	"vue":               iconSet["vue"],
	"ml":                iconSet["ocaml"],
	"mli":               iconSet["ocaml"],
	"cmx":               iconSet["ocaml"],
	"lock":              iconSet["lock"],
	"hbs":               iconSet["handlebars"],
	"mustache":          iconSet["handlebars"],
	"pm":                iconSet["perl"],
	"raku":              iconSet["perl"],
	"hx":                iconSet["haxe"],
	"pp":                iconSet["puppet"],
	"ex":                iconSet["elixir"],
	"exs":               iconSet["elixir"],
	"eex":               iconSet["elixir"],
	"leex":              iconSet["elixir"],
	"erl":               iconSet["erlang"],
	"twig":              iconSet["twig"],
	"jl":                iconSet["julia"],
	"elm":               iconSet["elm"],
	"pure":              iconSet["purescript"],
	"purs":              iconSet["purescript"],
	"tpl":               iconSet["smarty"],
	"styl":              iconSet["stylus"],
	"merlin":            iconSet["merlin"],
	"v":                 iconSet["verilog"],
	"vhd":               iconSet["verilog"],
	"sv":                iconSet["verilog"],
	"svh":               iconSet["verilog"],
	"robot":             iconSet["robot"],
	"sol":               iconSet["solidity"],
	"yang":              iconSet["yang"],
	"mjml":              iconSet["mjml"],
	"tf":                iconSet["terraform"],
	"tfvars":            iconSet["terraform"],
	"tfstate":           iconSet["terraform"],
	"applescript":       iconSet["applescript"],
	"ipa":               iconSet["applescript"],
	"cake":              iconSet["cake"],
	"nim":               iconSet["nim"],
	"nimble":            iconSet["nim"],
	"apib":              iconSet["apiblueprint"],
	"apiblueprint":      iconSet["apiblueprint"],
	"pcss":              iconSet["postcss"],
	"sss":               iconSet["postcss"],
	"todo":              iconSet["todo"],
	"nix":               iconSet["nix"],
	"slim":              iconSet["slim"],
	"http":              iconSet["http"],
	"rest":              iconSet["http"],
	"apk":               iconSet["android"],
	"env":               iconSet["tune"],
	"jenkinsfile":       iconSet["jenkins"],
	"jenkins":           iconSet["jenkins"],
	"log":               iconSet["log"],
	"ejs":               iconSet["ejs"],
	"djt":               iconSet["django"],
	"pot":               iconSet["i18n"],
	"po":                iconSet["i18n"],
	"mo":                iconSet["i18n"],
	"d":                 iconSet["d"],
	"mdx":               iconSet["mdx"],
	"gd":                iconSet["godot"],
	"godot":             iconSet["godot-assets"],
	"tres":              iconSet["godot-assets"],
	"tscn":              iconSet["godot-assets"],
	"azcli":             iconSet["azure"],
	"vagrantfile":       iconSet["vagrant"],
	"cshtml":            iconSet["razor"],
	"vbhtml":            iconSet["razor"],
	"ad":                iconSet["asciidoc"],
	"adoc":              iconSet["asciidoc"],
	"asciidoc":          iconSet["asciidoc"],
	"edge":              iconSet["edge"],
	"ss":                iconSet["scheme"],
	"scm":               iconSet["scheme"],
	"stl":               iconSet["3d"],
	"obj":               iconSet["3d"],
	"ac":                iconSet["3d"],
	"blend":             iconSet["3d"],
	"mesh":              iconSet["3d"],
	"mqo":               iconSet["3d"],
	"pmd":               iconSet["3d"],
	"pmx":               iconSet["3d"],
	"skp":               iconSet["3d"],
	"vac":               iconSet["3d"],
	"vdp":               iconSet["3d"],
	"vox":               iconSet["3d"],
	"svg":               iconSet["svg"],
	"vimrc":             iconSet["vim"],
	"gvimrc":            iconSet["vim"],
	"exrc":              iconSet["vim"],
	"moon":              iconSet["moonscript"],
	"iso":               iconSet["disc"],
	"f":                 iconSet["fortran"],
	"f77":               iconSet["fortran"],
	"f90":               iconSet["fortran"],
	"f95":               iconSet["fortran"],
	"f03":               iconSet["fortran"],
	"f08":               iconSet["fortran"],
	"tcl":               iconSet["tcl"],
	"liquid":            iconSet["liquid"],
	"p":                 iconSet["prolog"],
	"pro":               iconSet["prolog"],
	"coco":              iconSet["coconut"],
	"sketch":            iconSet["sketch"],
	"opam":              iconSet["opam"],
	"dhallb":            iconSet["dhall"],
	"pwn":               iconSet["pawn"],
	"amx":               iconSet["pawn"],
	"dhall":             iconSet["dhall"],
	"pas":               iconSet["pascal"],
	"unity":             iconSet["shaderlab"],
	"nupkg":             iconSet["nuget"],
	"command":           iconSet["command"],
	"dsc":               iconSet["denizenscript"],
	"deb":               iconSet["debian"],
	"rpm":               iconSet["redhat"],
	"snap":              iconSet["ubuntu"],
	"ebuild":            iconSet["gentoo"],
	"pkg":               iconSet["applescript"],
	"openbsd":           iconSet["freebsd"],
	// "ls":                Icon_Set["livescript"],
	// "re":                Icon_Set["reason"],
	// "rei":               Icon_Set["reason"],
	// "cmj":               Icon_Set["bucklescript"],
	// "nb":                Icon_Set["mathematica"],
	// "wl":                Icon_Set["wolframlanguage"],
	// "wls":               Icon_Set["wolframlanguage"],
	// "njk":               Icon_Set["nunjucks"],
	// "nunjucks":          Icon_Set["nunjucks"],
	// "au3":               Icon_Set["autoit"],
	// "haml":              Icon_Set["haml"],
	// "feature":           Icon_Set["cucumber"],
	// "riot":              Icon_Set["riot"],
	// "tag":               Icon_Set["riot"],
	// "vfl":               Icon_Set["vfl"],
	// "kl":                Icon_Set["kl"],
	// "cfml":              Icon_Set["coldfusion"],
	// "cfc":               Icon_Set["coldfusion"],
	// "lucee":             Icon_Set["coldfusion"],
	// "cfm":               Icon_Set["coldfusion"],
	// "cabal":             Icon_Set["cabal"],
	// "rql":               Icon_Set["restql"],
	// "restql":            Icon_Set["restql"],
	// "kv":                Icon_Set["kivy"],
	// "graphcool":         Icon_Set["graphcool"],
	// "sbt":               Icon_Set["sbt"],
	// "cr":                Icon_Set["crystal"],
	// "ecr":               Icon_Set["crystal"],
	// "cu":                Icon_Set["cuda"],
	// "cuh":               Icon_Set["cuda"],
	// "def":               Icon_Set["dotjs"],
	// "dot":               Icon_Set["dotjs"],
	// "jst":               Icon_Set["dotjs"],
	// "pde":               Icon_Set["processing"],
	// "wpy":               Icon_Set["wepy"],
	// "hcl":               Icon_Set["hcl"],
	// "san":               Icon_Set["san"],
	// "red":               Icon_Set["red"],
	// "fxp":               Icon_Set["foxpro"],
	// "prg":               Icon_Set["foxpro"],
	// "wat":               Icon_Set["webassembly"],
	// "wasm":              Icon_Set["webassembly"],
	// "ipynb":             Icon_Set["jupyter"],
	// "bal":               Icon_Set["ballerina"],
	// "balx":              Icon_Set["ballerina"],
	// "rkt":               Icon_Set["racket"],
	// "bzl":               Icon_Set["bazel"],
	// "bazel":             Icon_Set["bazel"],
	// "mint":              Icon_Set["mint"],
	// "vm":                Icon_Set["velocity"],
	// "fhtml":             Icon_Set["velocity"],
	// "vtl":               Icon_Set["velocity"],
	// "prisma":            Icon_Set["prisma"],
	// "abc":               Icon_Set["abc"],
	// "lisp":              Icon_Set["lisp"],
	// "lsp":               Icon_Set["lisp"],
	// "cl":                Icon_Set["lisp"],
	// "fast":              Icon_Set["lisp"],
	// "svelte":            Icon_Set["svelte"],
	// "prw":               Icon_Set["advpl_prw"],
	// "prx":               Icon_Set["advpl_prw"],
	// "ptm":               Icon_Set["advpl_ptm"],
	// "tlpp":              Icon_Set["advpl_tlpp"],
	// "ch":                Icon_Set["advpl_include"],
	// "4th":               Icon_Set["forth"],
	// "fth":               Icon_Set["forth"],
	// "frt":               Icon_Set["forth"],
	// "iuml":              Icon_Set["uml"],
	// "pu":                Icon_Set["uml"],
	// "puml":              Icon_Set["uml"],
	// "plantuml":          Icon_Set["uml"],
	// "wsd":               Icon_Set["uml"],
	// "sml":               Icon_Set["sml"],
	// "mlton":             Icon_Set["sml"],
	// "mlb":               Icon_Set["sml"],
	// "sig":               Icon_Set["sml"],
	// "fun":               Icon_Set["sml"],
	// "cm":                Icon_Set["sml"],
	// "lex":               Icon_Set["sml"],
	// "use":               Icon_Set["sml"],
	// "grm":               Icon_Set["sml"],
	// "imba":              Icon_Set["imba"],
	// "drawio":            Icon_Set["drawio"],
	// "dio":               Icon_Set["drawio"],
	// "sas":               Icon_Set["sas"],
	// "sas7bdat":          Icon_Set["sas"],
	// "sashdat":           Icon_Set["sas"],
	// "astore":            Icon_Set["sas"],
	// "ast":               Icon_Set["sas"],
	// "sast":              Icon_Set["sas"],
}
