// MIT License

// Copyright (c) 2020 Yash Handa

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package icons

var iconFileName = map[string]Icon{
	".pug-lintrc":                         iconSet["pug"],
	".pug-lintrc.js":                      iconSet["pug"],
	".pug-lintrc.json":                    iconSet["pug"],
	".jscsrc":                             iconSet["json"],
	".jshintrc":                           iconSet["json"],
	"composer.lock":                       iconSet["json"],
	".jsbeautifyrc":                       iconSet["json"],
	".esformatter":                        iconSet["json"],
	"cdp.pid":                             iconSet["json"],
	".mjmlconfig":                         iconSet["json"],
	".htaccess":                           iconSet["xml"],
	".jshintignore":                       iconSet["settings"],
	".buildignore":                        iconSet["settings"],
	".mrconfig":                           iconSet["settings"],
	".yardopts":                           iconSet["settings"],
	"manifest.mf":                         iconSet["settings"],
	".clang-format":                       iconSet["settings"],
	".clang-tidy":                         iconSet["settings"],
	"go.mod":                              iconSet["go-mod"],
	"go.sum":                              iconSet["go-mod"],
	"requirements.txt":                    iconSet["python-misc"],
	"pipfile":                             iconSet["python-misc"],
	".python-version":                     iconSet["python-misc"],
	"manifest.in":                         iconSet["python-misc"],
	"gradle.properties":                   iconSet["gradle"],
	"gradlew":                             iconSet["gradle"],
	"gradle-wrapper.properties":           iconSet["gradle"],
	"license":                             iconSet["certificate"],
	"license.md":                          iconSet["certificate"],
	"license.txt":                         iconSet["certificate"],
	"licence":                             iconSet["certificate"],
	"licence.md":                          iconSet["certificate"],
	"licence.txt":                         iconSet["certificate"],
	"unlicense":                           iconSet["certificate"],
	"unlicense.md":                        iconSet["certificate"],
	"unlicense.txt":                       iconSet["certificate"],
	".htpasswd":                           iconSet["key"],
	"gemfile":                             iconSet["gemfile"],
	"dockerfile":                          iconSet["docker"],
	"dockerfile.prod":                     iconSet["docker"],
	"dockerfile.production":               iconSet["docker"],
	"docker-compose.yml":                  iconSet["docker"],
	"docker-compose.yaml":                 iconSet["docker"],
	"docker-compose.dev.yml":              iconSet["docker"],
	"docker-compose.local.yml":            iconSet["docker"],
	"docker-compose.ci.yml":               iconSet["docker"],
	"docker-compose.override.yml":         iconSet["docker"],
	"docker-compose.staging.yml":          iconSet["docker"],
	"docker-compose.prod.yml":             iconSet["docker"],
	"docker-compose.production.yml":       iconSet["docker"],
	"docker-compose.test.yml":             iconSet["docker"],
	".mailmap":                            iconSet["email"],
	".graphqlconfig":                      iconSet["graphql"],
	".gitignore":                          iconSet["git"],
	".gitconfig":                          iconSet["git"],
	".gitattributes":                      iconSet["git"],
	".gitmodules":                         iconSet["git"],
	".gitkeep":                            iconSet["git"],
	"git-history":                         iconSet["git"],
	".luacheckrc":                         iconSet["lua"],
	".Rhistory":                           iconSet["r"],
	"cmakelists.txt":                      iconSet["cmake"],
	"cmakecache.txt":                      iconSet["cmake"],
	"vue.config.js":                       iconSet["vue-config"],
	"vue.config.ts":                       iconSet["vue-config"],
	"nuxt.config.js":                      iconSet["nuxt"],
	"nuxt.config.ts":                      iconSet["nuxt"],
	"security.md":                         iconSet["lock"],
	"security.txt":                        iconSet["lock"],
	"security":                            iconSet["lock"],
	"vercel.json":                         iconSet["vercel"],
	".vercelignore":                       iconSet["vercel"],
	"now.json":                            iconSet["vercel"],
	".nowignore":                          iconSet["vercel"],
	"postcss.config.js":                   iconSet["postcss"],
	".postcssrc.js":                       iconSet["postcss"],
	".postcssrc":                          iconSet["postcss"],
	".postcssrc.json":                     iconSet["postcss"],
	".postcssrc.yml":                      iconSet["postcss"],
	"CNAME":                               iconSet["http"],
	"webpack.js":                          iconSet["webpack"],
	"webpack.ts":                          iconSet["webpack"],
	"webpack.base.js":                     iconSet["webpack"],
	"webpack.base.ts":                     iconSet["webpack"],
	"webpack.config.js":                   iconSet["webpack"],
	"webpack.config.ts":                   iconSet["webpack"],
	"webpack.common.js":                   iconSet["webpack"],
	"webpack.common.ts":                   iconSet["webpack"],
	"webpack.config.common.js":            iconSet["webpack"],
	"webpack.config.common.ts":            iconSet["webpack"],
	"webpack.config.common.babel.js":      iconSet["webpack"],
	"webpack.config.common.babel.ts":      iconSet["webpack"],
	"webpack.dev.js":                      iconSet["webpack"],
	"webpack.dev.ts":                      iconSet["webpack"],
	"webpack.development.js":              iconSet["webpack"],
	"webpack.development.ts":              iconSet["webpack"],
	"webpack.config.dev.js":               iconSet["webpack"],
	"webpack.config.dev.ts":               iconSet["webpack"],
	"webpack.config.dev.babel.js":         iconSet["webpack"],
	"webpack.config.dev.babel.ts":         iconSet["webpack"],
	"webpack.prod.js":                     iconSet["webpack"],
	"webpack.prod.ts":                     iconSet["webpack"],
	"webpack.production.js":               iconSet["webpack"],
	"webpack.production.ts":               iconSet["webpack"],
	"webpack.server.js":                   iconSet["webpack"],
	"webpack.server.ts":                   iconSet["webpack"],
	"webpack.client.js":                   iconSet["webpack"],
	"webpack.client.ts":                   iconSet["webpack"],
	"webpack.config.server.js":            iconSet["webpack"],
	"webpack.config.server.ts":            iconSet["webpack"],
	"webpack.config.client.js":            iconSet["webpack"],
	"webpack.config.client.ts":            iconSet["webpack"],
	"webpack.config.production.babel.js":  iconSet["webpack"],
	"webpack.config.production.babel.ts":  iconSet["webpack"],
	"webpack.config.prod.babel.js":        iconSet["webpack"],
	"webpack.config.prod.babel.ts":        iconSet["webpack"],
	"webpack.config.prod.js":              iconSet["webpack"],
	"webpack.config.prod.ts":              iconSet["webpack"],
	"webpack.config.production.js":        iconSet["webpack"],
	"webpack.config.production.ts":        iconSet["webpack"],
	"webpack.config.staging.js":           iconSet["webpack"],
	"webpack.config.staging.ts":           iconSet["webpack"],
	"webpack.config.babel.js":             iconSet["webpack"],
	"webpack.config.babel.ts":             iconSet["webpack"],
	"webpack.config.base.babel.js":        iconSet["webpack"],
	"webpack.config.base.babel.ts":        iconSet["webpack"],
	"webpack.config.base.js":              iconSet["webpack"],
	"webpack.config.base.ts":              iconSet["webpack"],
	"webpack.config.staging.babel.js":     iconSet["webpack"],
	"webpack.config.staging.babel.ts":     iconSet["webpack"],
	"webpack.config.coffee":               iconSet["webpack"],
	"webpack.config.test.js":              iconSet["webpack"],
	"webpack.config.test.ts":              iconSet["webpack"],
	"webpack.config.vendor.js":            iconSet["webpack"],
	"webpack.config.vendor.ts":            iconSet["webpack"],
	"webpack.config.vendor.production.js": iconSet["webpack"],
	"webpack.config.vendor.production.ts": iconSet["webpack"],
	"webpack.test.js":                     iconSet["webpack"],
	"webpack.test.ts":                     iconSet["webpack"],
	"webpack.dist.js":                     iconSet["webpack"],
	"webpack.dist.ts":                     iconSet["webpack"],
	"webpackfile.js":                      iconSet["webpack"],
	"webpackfile.ts":                      iconSet["webpack"],
	"ionic.config.json":                   iconSet["ionic"],
	".io-config.json":                     iconSet["ionic"],
	"gulpfile.js":                         iconSet["gulp"],
	"gulpfile.mjs":                        iconSet["gulp"],
	"gulpfile.ts":                         iconSet["gulp"],
	"gulpfile.babel.js":                   iconSet["gulp"],
	"package.json":                        iconSet["nodejs"],
	"package-lock.json":                   iconSet["nodejs"],
	".nvmrc":                              iconSet["nodejs"],
	".esmrc":                              iconSet["nodejs"],
	".node-version":                       iconSet["nodejs"],
	".npmignore":                          iconSet["npm"],
	".npmrc":                              iconSet["npm"],
	".yarnrc":                             iconSet["yarn"],
	"yarn.lock":                           iconSet["yarn"],
	".yarnclean":                          iconSet["yarn"],
	".yarn-integrity":                     iconSet["yarn"],
	"yarn-error.log":                      iconSet["yarn"],
	".yarnrc.yml":                         iconSet["yarn"],
	".yarnrc.yaml":                        iconSet["yarn"],
	"androidmanifest.xml":                 iconSet["android"],
	".env.defaults":                       iconSet["tune"],
	".env.example":                        iconSet["tune"],
	".env.sample":                         iconSet["tune"],
	".env.schema":                         iconSet["tune"],
	".env.local":                          iconSet["tune"],
	".env.dev":                            iconSet["tune"],
	".env.development":                    iconSet["tune"],
	".env.qa":                             iconSet["tune"],
	".env.prod":                           iconSet["tune"],
	".env.production":                     iconSet["tune"],
	".env.staging":                        iconSet["tune"],
	".env.preview":                        iconSet["tune"],
	".env.test":                           iconSet["tune"],
	".env.testing":                        iconSet["tune"],
	".env.development.local":              iconSet["tune"],
	".env.qa.local":                       iconSet["tune"],
	".env.production.local":               iconSet["tune"],
	".env.staging.local":                  iconSet["tune"],
	".env.test.local":                     iconSet["tune"],
	".babelrc":                            iconSet["babel"],
	".babelrc.js":                         iconSet["babel"],
	".babelrc.json":                       iconSet["babel"],
	"babel.config.json":                   iconSet["babel"],
	"babel.config.js":                     iconSet["babel"],
	"contributing.md":                     iconSet["contributing"],
	"readme.md":                           iconSet["readme"],
	"readme.txt":                          iconSet["readme"],
	"readme":                              iconSet["readme"],
	"changelog":                           iconSet["changelog"],
	"changelog.md":                        iconSet["changelog"],
	"changelog.txt":                       iconSet["changelog"],
	"changes":                             iconSet["changelog"],
	"changes.md":                          iconSet["changelog"],
	"changes.txt":                         iconSet["changelog"],
	"credits":                             iconSet["credits"],
	"credits.txt":                         iconSet["credits"],
	"credits.md":                          iconSet["credits"],
	"authors":                             iconSet["authors"],
	"authors.md":                          iconSet["authors"],
	"authors.txt":                         iconSet["authors"],
	"favicon.ico":                         iconSet["favicon"],
	"karma.conf.js":                       iconSet["karma"],
	"karma.conf.ts":                       iconSet["karma"],
	"karma.conf.coffee":                   iconSet["karma"],
	"karma.config.js":                     iconSet["karma"],
	"karma.config.ts":                     iconSet["karma"],
	"karma-main.js":                       iconSet["karma"],
	"karma-main.ts":                       iconSet["karma"],
	".travis.yml":                         iconSet["travis"],
	".codecov.yml":                        iconSet["codecov"],
	"codecov.yml":                         iconSet["codecov"],
	"protractor.conf.js":                  iconSet["protractor"],
	"protractor.conf.ts":                  iconSet["protractor"],
	"protractor.conf.coffee":              iconSet["protractor"],
	"protractor.config.js":                iconSet["protractor"],
	"protractor.config.ts":                iconSet["protractor"],
	"procfile":                            iconSet["heroku"],
	"procfile.windows":                    iconSet["heroku"],
	".bowerrc":                            iconSet["bower"],
	"bower.json":                          iconSet["bower"],
	".eslintrc.js":                        iconSet["eslint"],
	".eslintrc.cjs":                       iconSet["eslint"],
	".eslintrc.yaml":                      iconSet["eslint"],
	".eslintrc.yml":                       iconSet["eslint"],
	".eslintrc.json":                      iconSet["eslint"],
	".eslintrc":                           iconSet["eslint"],
	".eslintignore":                       iconSet["eslint"],
	".eslintcache":                        iconSet["eslint"],
	"code_of_conduct.md":                  iconSet["conduct"],
	"code_of_conduct.txt":                 iconSet["conduct"],
	"mocha.opts":                          iconSet["mocha"],
	".mocharc.yml":                        iconSet["mocha"],
	".mocharc.yaml":                       iconSet["mocha"],
	".mocharc.js":                         iconSet["mocha"],
	".mocharc.json":                       iconSet["mocha"],
	".mocharc.jsonc":                      iconSet["mocha"],
	"jenkinsfile":                         iconSet["jenkins"],
	"firebase.json":                       iconSet["firebase"],
	".firebaserc":                         iconSet["firebase"],
	"firestore.rules":                     iconSet["firebase"],
	"firestore.indexes.json":              iconSet["firebase"],
	".stylelintrc":                        iconSet["stylelint"],
	"stylelint.config.js":                 iconSet["stylelint"],
	".stylelintrc.json":                   iconSet["stylelint"],
	".stylelintrc.yaml":                   iconSet["stylelint"],
	".stylelintrc.yml":                    iconSet["stylelint"],
	".stylelintrc.js":                     iconSet["stylelint"],
	".stylelintignore":                    iconSet["stylelint"],
	".codeclimate.yml":                    iconSet["code-climate"],
	".prettierrc":                         iconSet["prettier"],
	"prettier.config.js":                  iconSet["prettier"],
	".prettierrc.js":                      iconSet["prettier"],
	".prettierrc.json":                    iconSet["prettier"],
	".prettierrc.yaml":                    iconSet["prettier"],
	".prettierrc.yml":                     iconSet["prettier"],
	".prettierignore":                     iconSet["prettier"],
	"gruntfile.js":                        iconSet["grunt"],
	"gruntfile.ts":                        iconSet["grunt"],
	"gruntfile.coffee":                    iconSet["grunt"],
	"gruntfile.babel.js":                  iconSet["grunt"],
	"gruntfile.babel.ts":                  iconSet["grunt"],
	"gruntfile.babel.coffee":              iconSet["grunt"],
	"jest.config.js":                      iconSet["jest"],
	"jest.config.ts":                      iconSet["jest"],
	"jest.config.cjs":                     iconSet["jest"],
	"jest.config.mjs":                     iconSet["jest"],
	"jest.config.json":                    iconSet["jest"],
	"jest.e2e.config.js":                  iconSet["jest"],
	"jest.e2e.config.ts":                  iconSet["jest"],
	"jest.e2e.config.cjs":                 iconSet["jest"],
	"jest.e2e.config.mjs":                 iconSet["jest"],
	"jest.e2e.config.json":                iconSet["jest"],
	"jest.setup.js":                       iconSet["jest"],
	"jest.setup.ts":                       iconSet["jest"],
	"jest.json":                           iconSet["jest"],
	".jestrc":                             iconSet["jest"],
	".jestrc.js":                          iconSet["jest"],
	".jestrc.json":                        iconSet["jest"],
	"jest.teardown.js":                    iconSet["jest"],
	"fastfile":                            iconSet["fastlane"],
	"appfile":                             iconSet["fastlane"],
	".helmignore":                         iconSet["helm"],
	"makefile":                            iconSet["makefile"],
	".releaserc":                          iconSet["semantic-release"],
	".releaserc.yaml":                     iconSet["semantic-release"],
	".releaserc.yml":                      iconSet["semantic-release"],
	".releaserc.json":                     iconSet["semantic-release"],
	".releaserc.js":                       iconSet["semantic-release"],
	"release.config.js":                   iconSet["semantic-release"],
	"bitbucket-pipelines.yaml":            iconSet["bitbucket"],
	"bitbucket-pipelines.yml":             iconSet["bitbucket"],
	"azure-pipelines.yml":                 iconSet["azure-pipelines"],
	"azure-pipelines.yaml":                iconSet["azure-pipelines"],
	"vagrantfile":                         iconSet["vagrant"],
	"tailwind.js":                         iconSet["tailwindcss"],
	"tailwind.config.js":                  iconSet["tailwindcss"],
	"codeowners":                          iconSet["codeowners"],
	".gcloudignore":                       iconSet["gcp"],
	".huskyrc":                            iconSet["husky"],
	"husky.config.js":                     iconSet["husky"],
	".huskyrc.json":                       iconSet["husky"],
	".huskyrc.js":                         iconSet["husky"],
	".huskyrc.yaml":                       iconSet["husky"],
	".huskyrc.yml":                        iconSet["husky"],
	".commitlintrc":                       iconSet["commitlint"],
	".commitlintrc.js":                    iconSet["commitlint"],
	"commitlint.config.js":                iconSet["commitlint"],
	".commitlintrc.json":                  iconSet["commitlint"],
	".commitlint.yaml":                    iconSet["commitlint"],
	".commitlint.yml":                     iconSet["commitlint"],
	"dune":                                iconSet["dune"],
	"dune-project":                        iconSet["dune"],
	"roadmap.md":                          iconSet["roadmap"],
	"roadmap.txt":                         iconSet["roadmap"],
	"timeline.md":                         iconSet["roadmap"],
	"timeline.txt":                        iconSet["roadmap"],
	"milestones.md":                       iconSet["roadmap"],
	"milestones.txt":                      iconSet["roadmap"],
	"nuget.config":                        iconSet["nuget"],
	".nuspec":                             iconSet["nuget"],
	"nuget.exe":                           iconSet["nuget"],
	"stryker.conf.js":                     iconSet["stryker"],
	"stryker.conf.json":                   iconSet["stryker"],
	".modernizrrc":                        iconSet["modernizr"],
	".modernizrrc.js":                     iconSet["modernizr"],
	".modernizrrc.json":                   iconSet["modernizr"],
	"routing.ts":                          iconSet["routing"],
	"routing.tsx":                         iconSet["routing"],
	"routing.js":                          iconSet["routing"],
	"routing.jsx":                         iconSet["routing"],
	"routes.ts":                           iconSet["routing"],
	"routes.tsx":                          iconSet["routing"],
	"routes.js":                           iconSet["routing"],
	"routes.jsx":                          iconSet["routing"],
	// ".vfl":                                Icon_Set["vfl"],
	// ".kl":                                 Icon_Set["kl"],
	// "project.graphcool":                   Icon_Set["graphcool"],
	// ".flowconfig":                         Icon_Set["flow"],
	// ".bithoundrc":                         Icon_Set["bithound"],
	// ".appveyor.yml":                       Icon_Set["appveyor"],
	// "appveyor.yml":                        Icon_Set["appveyor"],
	// "fuse.js":                             Icon_Set["fusebox"],
	// ".editorconfig":                       Icon_Set["editorconfig"],
	// ".watchmanconfig":                     Icon_Set["watchman"],
	// "aurelia.json":                        Icon_Set["aurelia"],
	// "rollup.config.js":                    Icon_Set["rollup"],
	// "rollup.config.ts":                    Icon_Set["rollup"],
	// "rollup-config.js":                    Icon_Set["rollup"],
	// "rollup-config.ts":                    Icon_Set["rollup"],
	// "rollup.config.common.js":             Icon_Set["rollup"],
	// "rollup.config.common.ts":             Icon_Set["rollup"],
	// "rollup.config.base.js":               Icon_Set["rollup"],
	// "rollup.config.base.ts":               Icon_Set["rollup"],
	// "rollup.config.prod.js":               Icon_Set["rollup"],
	// "rollup.config.prod.ts":               Icon_Set["rollup"],
	// "rollup.config.dev.js":                Icon_Set["rollup"],
	// "rollup.config.dev.ts":                Icon_Set["rollup"],
	// "rollup.config.prod.vendor.js":        Icon_Set["rollup"],
	// "rollup.config.prod.vendor.ts":        Icon_Set["rollup"],
	// ".hhconfig":                           Icon_Set["hack"],
	// "apollo.config.js":                    Icon_Set["apollo"],
	// "nodemon.json":                        Icon_Set["nodemon"],
	// "nodemon-debug.json":                  Icon_Set["nodemon"],
	// ".hintrc":                             Icon_Set["webhint"],
	// "browserslist":                        Icon_Set["browserlist"],
	// ".browserslistrc":                     Icon_Set["browserlist"],
	// ".snyk":                               Icon_Set["snyk"],
	// ".drone.yml":                          Icon_Set["drone"],
	// ".sequelizerc":                        Icon_Set["sequelize"],
	// "gatsby.config.js":                    Icon_Set["gatsby"],
	// "gatsby-config.js":                    Icon_Set["gatsby"],
	// "gatsby-node.js":                      Icon_Set["gatsby"],
	// "gatsby-browser.js":                   Icon_Set["gatsby"],
	// "gatsby-ssr.js":                       Icon_Set["gatsby"],
	// ".wakatime-project":                   Icon_Set["wakatime"],
	// "circle.yml":                          Icon_Set["circleci"],
	// ".cfignore":                           Icon_Set["cloudfoundry"],
	// "wallaby.js":                          Icon_Set["wallaby"],
	// "wallaby.conf.js":                     Icon_Set["wallaby"],
	// "stencil.config.js":                   Icon_Set["stencil"],
	// "stencil.config.ts":                   Icon_Set["stencil"],
	// ".bazelignore":                        Icon_Set["bazel"],
	// ".bazelrc":                            Icon_Set["bazel"],
	// "prisma.yml":                          Icon_Set["prisma"],
	// ".nycrc":                              Icon_Set["istanbul"],
	// ".nycrc.json":                         Icon_Set["istanbul"],
	// "buildkite.yml":                       Icon_Set["buildkite"],
	// "buildkite.yaml":                      Icon_Set["buildkite"],
	// "netlify.json":                        Icon_Set["netlify"],
	// "netlify.yml":                         Icon_Set["netlify"],
	// "netlify.yaml":                        Icon_Set["netlify"],
	// "netlify.toml":                        Icon_Set["netlify"],
	// "nest-cli.json":                       Icon_Set["nest"],
	// ".nest-cli.json":                      Icon_Set["nest"],
	// "nestconfig.json":                     Icon_Set["nest"],
	// ".nestconfig.json":                    Icon_Set["nest"],
	// ".percy.yml":                          Icon_Set["percy"],
	// ".gitpod.yml":                         Icon_Set["gitpod"],
	// "tiltfile":                            Icon_Set["tilt"],
	// "capacitor.config.json":               Icon_Set["capacitor"],
	// ".adonisrc.json":                      Icon_Set["adonis"],
	// "ace":                                 Icon_Set["adonis"],
	// "meson.build":                         Icon_Set["meson"],
	// ".buckconfig":                         Icon_Set["buck"],
	// "nx.json":                             Icon_Set["nrwl"],
	// ".slugignore":                         Icon_Set["slug"],
}
