package main

// type iconDef struct {
// 	FontCharacter string `json:"fontCharacter"`
// 	FontColor     string `json:"fontColor"`
// }

// type IconDefinitions struct {
// 	RLight               RLight               `json:"_R_light"`
// 	R                    R                    `json:"_R"`
// 	ArgdownLight         ArgdownLight         `json:"_argdown_light"`
// 	Argdown              Argdown              `json:"_argdown"`
// 	AsmLight             AsmLight             `json:"_asm_light"`
// 	Asm                  Asm                  `json:"_asm"`
// 	AudioLight           AudioLight           `json:"_audio_light"`
// 	Audio                Audio                `json:"_audio"`
// 	BabelLight           BabelLight           `json:"_babel_light"`
// 	Babel                Babel                `json:"_babel"`
// 	BazelLight           BazelLight           `json:"_bazel_light"`
// 	Bazel                Bazel                `json:"_bazel"`
// 	Bazel1Light          Bazel1Light          `json:"_bazel_1_light"`
// 	Bazel1               Bazel1               `json:"_bazel_1"`
// 	BicepLight           BicepLight           `json:"_bicep_light"`
// 	Bicep                Bicep                `json:"_bicep"`
// 	BowerLight           BowerLight           `json:"_bower_light"`
// 	Bower                Bower                `json:"_bower"`
// 	BslLight             BslLight             `json:"_bsl_light"`
// 	Bsl                  Bsl                  `json:"_bsl"`
// 	CLight               CLight               `json:"_c_light"`
// 	C                    C                    `json:"_c"`
// 	CSharpLight          CSharpLight          `json:"_c-sharp_light"`
// 	CSharp               CSharp               `json:"_c-sharp"`
// 	C1Light              C1Light              `json:"_c_1_light"`
// 	C1                   C1                   `json:"_c_1"`
// 	C2Light              C2Light              `json:"_c_2_light"`
// 	C2                   C2                   `json:"_c_2"`
// 	CakeLight            CakeLight            `json:"_cake_light"`
// 	Cake                 Cake                 `json:"_cake"`
// 	CakePhpLight         CakePhpLight         `json:"_cake_php_light"`
// 	CakePhp              CakePhp              `json:"_cake_php"`
// 	ClockLight           ClockLight           `json:"_clock_light"`
// 	Clock                Clock                `json:"_clock"`
// 	Clock1Light          Clock1Light          `json:"_clock_1_light"`
// 	Clock1               Clock1               `json:"_clock_1"`
// 	ClojureLight         ClojureLight         `json:"_clojure_light"`
// 	Clojure              Clojure              `json:"_clojure"`
// 	Clojure1Light        Clojure1Light        `json:"_clojure_1_light"`
// 	Clojure1             Clojure1             `json:"_clojure_1"`
// 	CodeClimateLight     CodeClimateLight     `json:"_code-climate_light"`
// 	CodeClimate          CodeClimate          `json:"_code-climate"`
// 	CodeSearchLight      CodeSearchLight      `json:"_code-search_light"`
// 	CodeSearch           CodeSearch           `json:"_code-search"`
// 	CoffeeLight          CoffeeLight          `json:"_coffee_light"`
// 	Coffee               Coffee               `json:"_coffee"`
// 	ColdfusionLight      ColdfusionLight      `json:"_coldfusion_light"`
// 	Coldfusion           Coldfusion           `json:"_coldfusion"`
// 	ConfigLight          ConfigLight          `json:"_config_light"`
// 	Config               Config               `json:"_config"`
// 	CppLight             CppLight             `json:"_cpp_light"`
// 	Cpp                  Cpp                  `json:"_cpp"`
// 	Cpp1Light            Cpp1Light            `json:"_cpp_1_light"`
// 	Cpp1                 Cpp1                 `json:"_cpp_1"`
// 	Cpp2Light            Cpp2Light            `json:"_cpp_2_light"`
// 	Cpp2                 Cpp2                 `json:"_cpp_2"`
// 	CrystalLight         CrystalLight         `json:"_crystal_light"`
// 	Crystal              Crystal              `json:"_crystal"`
// 	CrystalEmbeddedLight CrystalEmbeddedLight `json:"_crystal_embedded_light"`
// 	CrystalEmbedded      CrystalEmbedded      `json:"_crystal_embedded"`
// 	CSSLight             CSSLight             `json:"_css_light"`
// 	CSS                  CSS                  `json:"_css"`
// 	CsvLight             CsvLight             `json:"_csv_light"`
// 	Csv                  Csv                  `json:"_csv"`
// 	CuLight              CuLight              `json:"_cu_light"`
// 	Cu                   Cu                   `json:"_cu"`
// 	Cu1Light             Cu1Light             `json:"_cu_1_light"`
// 	Cu1                  Cu1                  `json:"_cu_1"`
// 	DLight               DLight               `json:"_d_light"`
// 	D                    D                    `json:"_d"`
// 	DartLight            DartLight            `json:"_dart_light"`
// 	Dart                 Dart                 `json:"_dart"`
// 	DbLight              DbLight              `json:"_db_light"`
// 	Db                   Db                   `json:"_db"`
// 	Db1Light             Db1Light             `json:"_db_1_light"`
// 	Db1                  Db1                  `json:"_db_1"`
// 	DefaultLight         DefaultLight         `json:"_default_light"`
// 	Default              Default              `json:"_default"`
// 	DockerLight          DockerLight          `json:"_docker_light"`
// 	Docker               Docker               `json:"_docker"`
// 	Docker1Light         Docker1Light         `json:"_docker_1_light"`
// 	Docker1              Docker1              `json:"_docker_1"`
// 	Docker2Light         Docker2Light         `json:"_docker_2_light"`
// 	Docker2              Docker2              `json:"_docker_2"`
// 	Docker3Light         Docker3Light         `json:"_docker_3_light"`
// 	Docker3              Docker3              `json:"_docker_3"`
// 	EjsLight             EjsLight             `json:"_ejs_light"`
// 	Ejs                  Ejs                  `json:"_ejs"`
// 	ElixirLight          ElixirLight          `json:"_elixir_light"`
// 	Elixir               Elixir               `json:"_elixir"`
// 	ElixirScriptLight    ElixirScriptLight    `json:"_elixir_script_light"`
// 	ElixirScript         ElixirScript         `json:"_elixir_script"`
// 	ElmLight             ElmLight             `json:"_elm_light"`
// 	Elm                  Elm                  `json:"_elm"`
// 	EslintLight          EslintLight          `json:"_eslint_light"`
// 	Eslint               Eslint               `json:"_eslint"`
// 	Eslint1Light         Eslint1Light         `json:"_eslint_1_light"`
// 	Eslint1              Eslint1              `json:"_eslint_1"`
// 	EthereumLight        EthereumLight        `json:"_ethereum_light"`
// 	Ethereum             Ethereum             `json:"_ethereum"`
// 	FSharpLight          FSharpLight          `json:"_f-sharp_light"`
// 	FSharp               FSharp               `json:"_f-sharp"`
// 	FaviconLight         FaviconLight         `json:"_favicon_light"`
// 	Favicon              Favicon              `json:"_favicon"`
// 	FirebaseLight        FirebaseLight        `json:"_firebase_light"`
// 	Firebase             Firebase             `json:"_firebase"`
// 	FirefoxLight         FirefoxLight         `json:"_firefox_light"`
// 	Firefox              Firefox              `json:"_firefox"`
// 	FontLight            FontLight            `json:"_font_light"`
// 	Font                 Font                 `json:"_font"`
// 	GitLight             GitLight             `json:"_git_light"`
// 	Git                  Git                  `json:"_git"`
// 	GithubLight          GithubLight          `json:"_github_light"`
// 	Github               Github               `json:"_github"`
// 	GitlabLight          GitlabLight          `json:"_gitlab_light"`
// 	Gitlab               Gitlab               `json:"_gitlab"`
// 	GoLight              GoLight              `json:"_go_light"`
// 	Go                   Go                   `json:"_go"`
// 	Go2Light             Go2Light             `json:"_go2_light"`
// 	Go2                  Go2                  `json:"_go2"`
// 	GodotLight           GodotLight           `json:"_godot_light"`
// 	Godot                Godot                `json:"_godot"`
// 	Godot1Light          Godot1Light          `json:"_godot_1_light"`
// 	Godot1               Godot1               `json:"_godot_1"`
// 	Godot2Light          Godot2Light          `json:"_godot_2_light"`
// 	Godot2               Godot2               `json:"_godot_2"`
// 	Godot3Light          Godot3Light          `json:"_godot_3_light"`
// 	Godot3               Godot3               `json:"_godot_3"`
// 	GradleLight          GradleLight          `json:"_gradle_light"`
// 	Gradle               Gradle               `json:"_gradle"`
// 	GrailsLight          GrailsLight          `json:"_grails_light"`
// 	Grails               Grails               `json:"_grails"`
// 	GraphqlLight         GraphqlLight         `json:"_graphql_light"`
// 	Graphql              Graphql              `json:"_graphql"`
// 	GruntLight           GruntLight           `json:"_grunt_light"`
// 	Grunt                Grunt                `json:"_grunt"`
// 	GulpLight            GulpLight            `json:"_gulp_light"`
// 	Gulp                 Gulp                 `json:"_gulp"`
// 	HacklangLight        HacklangLight        `json:"_hacklang_light"`
// 	Hacklang             Hacklang             `json:"_hacklang"`
// 	HamlLight            HamlLight            `json:"_haml_light"`
// 	Haml                 Haml                 `json:"_haml"`
// 	HappeningsLight      HappeningsLight      `json:"_happenings_light"`
// 	Happenings           Happenings           `json:"_happenings"`
// 	HaskellLight         HaskellLight         `json:"_haskell_light"`
// 	Haskell              Haskell              `json:"_haskell"`
// 	HaxeLight            HaxeLight            `json:"_haxe_light"`
// 	Haxe                 Haxe                 `json:"_haxe"`
// 	Haxe1Light           Haxe1Light           `json:"_haxe_1_light"`
// 	Haxe1                Haxe1                `json:"_haxe_1"`
// 	Haxe2Light           Haxe2Light           `json:"_haxe_2_light"`
// 	Haxe2                Haxe2                `json:"_haxe_2"`
// 	Haxe3Light           Haxe3Light           `json:"_haxe_3_light"`
// 	Haxe3                Haxe3                `json:"_haxe_3"`
// 	HerokuLight          HerokuLight          `json:"_heroku_light"`
// 	Heroku               Heroku               `json:"_heroku"`
// 	HexLight             HexLight             `json:"_hex_light"`
// 	Hex                  Hex                  `json:"_hex"`
// 	HTMLLight            HTMLLight            `json:"_html_light"`
// 	HTML                 HTML                 `json:"_html"`
// 	HTML1Light           HTML1Light           `json:"_html_1_light"`
// 	HTML1                HTML1                `json:"_html_1"`
// 	HTML2Light           HTML2Light           `json:"_html_2_light"`
// 	HTML2                HTML2                `json:"_html_2"`
// 	HTML3Light           HTML3Light           `json:"_html_3_light"`
// 	HTML3                HTML3                `json:"_html_3"`
// 	HTMLErbLight         HTMLErbLight         `json:"_html_erb_light"`
// 	HTMLErb              HTMLErb              `json:"_html_erb"`
// 	IgnoredLight         IgnoredLight         `json:"_ignored_light"`
// 	Ignored              Ignored              `json:"_ignored"`
// 	IllustratorLight     IllustratorLight     `json:"_illustrator_light"`
// 	Illustrator          Illustrator          `json:"_illustrator"`
// 	ImageLight           ImageLight           `json:"_image_light"`
// 	Image                Image                `json:"_image"`
// 	InfoLight            InfoLight            `json:"_info_light"`
// 	Info                 Info                 `json:"_info"`
// 	IonicLight           IonicLight           `json:"_ionic_light"`
// 	Ionic                Ionic                `json:"_ionic"`
// 	JadeLight            JadeLight            `json:"_jade_light"`
// 	Jade                 Jade                 `json:"_jade"`
// 	JavaLight            JavaLight            `json:"_java_light"`
// 	Java                 Java                 `json:"_java"`
// 	Java1Light           Java1Light           `json:"_java_1_light"`
// 	Java1                Java1                `json:"_java_1"`
// 	JavascriptLight      JavascriptLight      `json:"_javascript_light"`
// 	Javascript           Javascript           `json:"_javascript"`
// 	Javascript1Light     Javascript1Light     `json:"_javascript_1_light"`
// 	Javascript1          Javascript1          `json:"_javascript_1"`
// 	Javascript2Light     Javascript2Light     `json:"_javascript_2_light"`
// 	Javascript2          Javascript2          `json:"_javascript_2"`
// 	JenkinsLight         JenkinsLight         `json:"_jenkins_light"`
// 	Jenkins              Jenkins              `json:"_jenkins"`
// 	JinjaLight           JinjaLight           `json:"_jinja_light"`
// 	Jinja                Jinja                `json:"_jinja"`
// 	JSONLight            JSONLight            `json:"_json_light"`
// 	JSON                 JSON                 `json:"_json"`
// 	JSON1Light           JSON1Light           `json:"_json_1_light"`
// 	JSON1                JSON1                `json:"_json_1"`
// 	JuliaLight           JuliaLight           `json:"_julia_light"`
// 	Julia                Julia                `json:"_julia"`
// 	KarmaLight           KarmaLight           `json:"_karma_light"`
// 	Karma                Karma                `json:"_karma"`
// 	KotlinLight          KotlinLight          `json:"_kotlin_light"`
// 	Kotlin               Kotlin               `json:"_kotlin"`
// 	LessLight            LessLight            `json:"_less_light"`
// 	Less                 Less                 `json:"_less"`
// 	LicenseLight         LicenseLight         `json:"_license_light"`
// 	License              License              `json:"_license"`
// 	License1Light        License1Light        `json:"_license_1_light"`
// 	License1             License1             `json:"_license_1"`
// 	License2Light        License2Light        `json:"_license_2_light"`
// 	License2             License2             `json:"_license_2"`
// 	LiquidLight          LiquidLight          `json:"_liquid_light"`
// 	Liquid               Liquid               `json:"_liquid"`
// 	LivescriptLight      LivescriptLight      `json:"_livescript_light"`
// 	Livescript           Livescript           `json:"_livescript"`
// 	LockLight            LockLight            `json:"_lock_light"`
// 	Lock                 Lock                 `json:"_lock"`
// 	LuaLight             LuaLight             `json:"_lua_light"`
// 	Lua                  Lua                  `json:"_lua"`
// 	MakefileLight        MakefileLight        `json:"_makefile_light"`
// 	Makefile             Makefile             `json:"_makefile"`
// 	Makefile1Light       Makefile1Light       `json:"_makefile_1_light"`
// 	Makefile1            Makefile1            `json:"_makefile_1"`
// 	Makefile2Light       Makefile2Light       `json:"_makefile_2_light"`
// 	Makefile2            Makefile2            `json:"_makefile_2"`
// 	Makefile3Light       Makefile3Light       `json:"_makefile_3_light"`
// 	Makefile3            Makefile3            `json:"_makefile_3"`
// 	MarkdownLight        MarkdownLight        `json:"_markdown_light"`
// 	Markdown             Markdown             `json:"_markdown"`
// 	MavenLight           MavenLight           `json:"_maven_light"`
// 	Maven                Maven                `json:"_maven"`
// 	MdoLight             MdoLight             `json:"_mdo_light"`
// 	Mdo                  Mdo                  `json:"_mdo"`
// 	MustacheLight        MustacheLight        `json:"_mustache_light"`
// 	Mustache             Mustache             `json:"_mustache"`
// 	NimLight             NimLight             `json:"_nim_light"`
// 	Nim                  Nim                  `json:"_nim"`
// 	NotebookLight        NotebookLight        `json:"_notebook_light"`
// 	Notebook             Notebook             `json:"_notebook"`
// 	NpmLight             NpmLight             `json:"_npm_light"`
// 	Npm                  Npm                  `json:"_npm"`
// 	Npm1Light            Npm1Light            `json:"_npm_1_light"`
// 	Npm1                 Npm1                 `json:"_npm_1"`
// 	NpmIgnoredLight      NpmIgnoredLight      `json:"_npm_ignored_light"`
// 	NpmIgnored           NpmIgnored           `json:"_npm_ignored"`
// 	NunjucksLight        NunjucksLight        `json:"_nunjucks_light"`
// 	Nunjucks             Nunjucks             `json:"_nunjucks"`
// 	OcamlLight           OcamlLight           `json:"_ocaml_light"`
// 	Ocaml                Ocaml                `json:"_ocaml"`
// 	OdataLight           OdataLight           `json:"_odata_light"`
// 	Odata                Odata                `json:"_odata"`
// 	PddlLight            PddlLight            `json:"_pddl_light"`
// 	Pddl                 Pddl                 `json:"_pddl"`
// 	PdfLight             PdfLight             `json:"_pdf_light"`
// 	Pdf                  Pdf                  `json:"_pdf"`
// 	PerlLight            PerlLight            `json:"_perl_light"`
// 	Perl                 Perl                 `json:"_perl"`
// 	PhotoshopLight       PhotoshopLight       `json:"_photoshop_light"`
// 	Photoshop            Photoshop            `json:"_photoshop"`
// 	PhpLight             PhpLight             `json:"_php_light"`
// 	Php                  Php                  `json:"_php"`
// 	PipelineLight        PipelineLight        `json:"_pipeline_light"`
// 	Pipeline             Pipeline             `json:"_pipeline"`
// 	PlanLight            PlanLight            `json:"_plan_light"`
// 	Plan                 Plan                 `json:"_plan"`
// 	PlatformioLight      PlatformioLight      `json:"_platformio_light"`
// 	Platformio           Platformio           `json:"_platformio"`
// 	PowershellLight      PowershellLight      `json:"_powershell_light"`
// 	Powershell           Powershell           `json:"_powershell"`
// 	PrismaLight          PrismaLight          `json:"_prisma_light"`
// 	Prisma               Prisma               `json:"_prisma"`
// 	PrologLight          PrologLight          `json:"_prolog_light"`
// 	Prolog               Prolog               `json:"_prolog"`
// 	PugLight             PugLight             `json:"_pug_light"`
// 	Pug                  Pug                  `json:"_pug"`
// 	PuppetLight          PuppetLight          `json:"_puppet_light"`
// 	Puppet               Puppet               `json:"_puppet"`
// 	PurescriptLight      PurescriptLight      `json:"_purescript_light"`
// 	Purescript           Purescript           `json:"_purescript"`
// 	PythonLight          PythonLight          `json:"_python_light"`
// 	Python               Python               `json:"_python"`
// 	ReactLight           ReactLight           `json:"_react_light"`
// 	React                React                `json:"_react"`
// 	React1Light          React1Light          `json:"_react_1_light"`
// 	React1               React1               `json:"_react_1"`
// 	ReasonmlLight        ReasonmlLight        `json:"_reasonml_light"`
// 	Reasonml             Reasonml             `json:"_reasonml"`
// 	RescriptLight        RescriptLight        `json:"_rescript_light"`
// 	Rescript             Rescript             `json:"_rescript"`
// 	Rescript1Light       Rescript1Light       `json:"_rescript_1_light"`
// 	Rescript1            Rescript1            `json:"_rescript_1"`
// 	RollupLight          RollupLight          `json:"_rollup_light"`
// 	Rollup               Rollup               `json:"_rollup"`
// 	RubyLight            RubyLight            `json:"_ruby_light"`
// 	Ruby                 Ruby                 `json:"_ruby"`
// 	RustLight            RustLight            `json:"_rust_light"`
// 	Rust                 Rust                 `json:"_rust"`
// 	SalesforceLight      SalesforceLight      `json:"_salesforce_light"`
// 	Salesforce           Salesforce           `json:"_salesforce"`
// 	SassLight            SassLight            `json:"_sass_light"`
// 	Sass                 Sass                 `json:"_sass"`
// 	SbtLight             SbtLight             `json:"_sbt_light"`
// 	Sbt                  Sbt                  `json:"_sbt"`
// 	ScalaLight           ScalaLight           `json:"_scala_light"`
// 	Scala                Scala                `json:"_scala"`
// 	ShellLight           ShellLight           `json:"_shell_light"`
// 	Shell                Shell                `json:"_shell"`
// 	SlimLight            SlimLight            `json:"_slim_light"`
// 	Slim                 Slim                 `json:"_slim"`
// 	SmartyLight          SmartyLight          `json:"_smarty_light"`
// 	Smarty               Smarty               `json:"_smarty"`
// 	SpringLight          SpringLight          `json:"_spring_light"`
// 	Spring               Spring               `json:"_spring"`
// 	StylelintLight       StylelintLight       `json:"_stylelint_light"`
// 	Stylelint            Stylelint            `json:"_stylelint"`
// 	Stylelint1Light      Stylelint1Light      `json:"_stylelint_1_light"`
// 	Stylelint1           Stylelint1           `json:"_stylelint_1"`
// 	StylusLight          StylusLight          `json:"_stylus_light"`
// 	Stylus               Stylus               `json:"_stylus"`
// 	SublimeLight         SublimeLight         `json:"_sublime_light"`
// 	Sublime              Sublime              `json:"_sublime"`
// 	SvelteLight          SvelteLight          `json:"_svelte_light"`
// 	Svelte               Svelte               `json:"_svelte"`
// 	SvgLight             SvgLight             `json:"_svg_light"`
// 	Svg                  Svg                  `json:"_svg"`
// 	Svg1Light            Svg1Light            `json:"_svg_1_light"`
// 	Svg1                 Svg1                 `json:"_svg_1"`
// 	SwiftLight           SwiftLight           `json:"_swift_light"`
// 	Swift                Swift                `json:"_swift"`
// 	TerraformLight       TerraformLight       `json:"_terraform_light"`
// 	Terraform            Terraform            `json:"_terraform"`
// 	TexLight             TexLight             `json:"_tex_light"`
// 	Tex                  Tex                  `json:"_tex"`
// 	Tex1Light            Tex1Light            `json:"_tex_1_light"`
// 	Tex1                 Tex1                 `json:"_tex_1"`
// 	Tex2Light            Tex2Light            `json:"_tex_2_light"`
// 	Tex2                 Tex2                 `json:"_tex_2"`
// 	Tex3Light            Tex3Light            `json:"_tex_3_light"`
// 	Tex3                 Tex3                 `json:"_tex_3"`
// 	Todo                 Todo                 `json:"_todo"`
// 	TsconfigLight        TsconfigLight        `json:"_tsconfig_light"`
// 	Tsconfig             Tsconfig             `json:"_tsconfig"`
// 	TwigLight            TwigLight            `json:"_twig_light"`
// 	Twig                 Twig                 `json:"_twig"`
// 	TypescriptLight      TypescriptLight      `json:"_typescript_light"`
// 	Typescript           Typescript           `json:"_typescript"`
// 	Typescript1Light     Typescript1Light     `json:"_typescript_1_light"`
// 	Typescript1          Typescript1          `json:"_typescript_1"`
// 	ValaLight            ValaLight            `json:"_vala_light"`
// 	Vala                 Vala                 `json:"_vala"`
// 	VideoLight           VideoLight           `json:"_video_light"`
// 	Video                Video                `json:"_video"`
// 	VueLight             VueLight             `json:"_vue_light"`
// 	Vue                  Vue                  `json:"_vue"`
// 	WasmLight            WasmLight            `json:"_wasm_light"`
// 	Wasm                 Wasm                 `json:"_wasm"`
// 	WatLight             WatLight             `json:"_wat_light"`
// 	Wat                  Wat                  `json:"_wat"`
// 	WebpackLight         WebpackLight         `json:"_webpack_light"`
// 	Webpack              Webpack              `json:"_webpack"`
// 	WgtLight             WgtLight             `json:"_wgt_light"`
// 	Wgt                  Wgt                  `json:"_wgt"`
// 	WindowsLight         WindowsLight         `json:"_windows_light"`
// 	Windows              Windows              `json:"_windows"`
// 	WordLight            WordLight            `json:"_word_light"`
// 	Word                 Word                 `json:"_word"`
// 	XlsLight             XlsLight             `json:"_xls_light"`
// 	Xls                  Xls                  `json:"_xls"`
// 	XMLLight             XMLLight             `json:"_xml_light"`
// 	XML                  XML                  `json:"_xml"`
// 	YarnLight            YarnLight            `json:"_yarn_light"`
// 	Yarn                 Yarn                 `json:"_yarn"`
// 	YmlLight             YmlLight             `json:"_yml_light"`
// 	Yml                  Yml                  `json:"_yml"`
// 	ZigLight             ZigLight             `json:"_zig_light"`
// 	Zig                  Zig                  `json:"_zig"`
// 	ZipLight             ZipLight             `json:"_zip_light"`
// 	Zip                  Zip                  `json:"_zip"`
// 	Zip1Light            Zip1Light            `json:"_zip_1_light"`
// 	Zip1                 Zip1                 `json:"_zip_1"`
// }
// type FileExtensions struct {
// 	Bsl              string `json:"bsl"`
// 	Mdo              string `json:"mdo"`
// 	Cls              string `json:"cls"`
// 	Apex             string `json:"apex"`
// 	Asm              string `json:"asm"`
// 	S                string `json:"s"`
// 	Bicep            string `json:"bicep"`
// 	Bzl              string `json:"bzl"`
// 	Bazel            string `json:"bazel"`
// 	Build            string `json:"build"`
// 	Workspace        string `json:"workspace"`
// 	Bazelignore      string `json:"bazelignore"`
// 	Bazelversion     string `json:"bazelversion"`
// 	H                string `json:"h"`
// 	Aspx             string `json:"aspx"`
// 	Ascx             string `json:"ascx"`
// 	Asax             string `json:"asax"`
// 	Master           string `json:"master"`
// 	Hh               string `json:"hh"`
// 	Hpp              string `json:"hpp"`
// 	Hxx              string `json:"hxx"`
// 	H0               string `json:"h++"`
// 	Edn              string `json:"edn"`
// 	Cfc              string `json:"cfc"`
// 	Cfm              string `json:"cfm"`
// 	Litcoffee        string `json:"litcoffee"`
// 	Config           string `json:"config"`
// 	Cr               string `json:"cr"`
// 	Ecr              string `json:"ecr"`
// 	Slang            string `json:"slang"`
// 	Cson             string `json:"cson"`
// 	CSSMap           string `json:"css.map"`
// 	Sss              string `json:"sss"`
// 	Csv              string `json:"csv"`
// 	Xls              string `json:"xls"`
// 	Xlsx             string `json:"xlsx"`
// 	Cuh              string `json:"cuh"`
// 	Hu               string `json:"hu"`
// 	Cake             string `json:"cake"`
// 	Ctp              string `json:"ctp"`
// 	D                string `json:"d"`
// 	Doc              string `json:"doc"`
// 	Docx             string `json:"docx"`
// 	Ejs              string `json:"ejs"`
// 	Ex               string `json:"ex"`
// 	Exs              string `json:"exs"`
// 	Elm              string `json:"elm"`
// 	Ico              string `json:"ico"`
// 	Gitconfig        string `json:"gitconfig"`
// 	Gitkeep          string `json:"gitkeep"`
// 	Gitattributes    string `json:"gitattributes"`
// 	Gitmodules       string `json:"gitmodules"`
// 	Slide            string `json:"slide"`
// 	Article          string `json:"article"`
// 	Gd               string `json:"gd"`
// 	Godot            string `json:"godot"`
// 	Tres             string `json:"tres"`
// 	Tscn             string `json:"tscn"`
// 	Gradle           string `json:"gradle"`
// 	Gsp              string `json:"gsp"`
// 	Gql              string `json:"gql"`
// 	Graphql          string `json:"graphql"`
// 	Graphqls         string `json:"graphqls"`
// 	Hack             string `json:"hack"`
// 	Haml             string `json:"haml"`
// 	Hs               string `json:"hs"`
// 	LHS              string `json:"lhs"`
// 	Hx               string `json:"hx"`
// 	Hxs              string `json:"hxs"`
// 	Hxp              string `json:"hxp"`
// 	Hxml             string `json:"hxml"`
// 	Jade             string `json:"jade"`
// 	Class            string `json:"class"`
// 	Classpath        string `json:"classpath"`
// 	JsMap            string `json:"js.map"`
// 	SpecJs           string `json:"spec.js"`
// 	TestJs           string `json:"test.js"`
// 	Es               string `json:"es"`
// 	Es5              string `json:"es5"`
// 	Es7              string `json:"es7"`
// 	Jinja            string `json:"jinja"`
// 	Jinja2           string `json:"jinja2"`
// 	Kt               string `json:"kt"`
// 	Kts              string `json:"kts"`
// 	Liquid           string `json:"liquid"`
// 	Ls               string `json:"ls"`
// 	Argdown          string `json:"argdown"`
// 	Ad               string `json:"ad"`
// 	Mustache         string `json:"mustache"`
// 	Stache           string `json:"stache"`
// 	Nim              string `json:"nim"`
// 	Nims             string `json:"nims"`
// 	GithubIssues     string `json:"github-issues"`
// 	Ipynb            string `json:"ipynb"`
// 	Njk              string `json:"njk"`
// 	Nunjucks         string `json:"nunjucks"`
// 	Nunjs            string `json:"nunjs"`
// 	Nunj             string `json:"nunj"`
// 	Njs              string `json:"njs"`
// 	Nj               string `json:"nj"`
// 	NpmDebugLog      string `json:"npm-debug.log"`
// 	Npmignore        string `json:"npmignore"`
// 	Npmrc            string `json:"npmrc"`
// 	Ml               string `json:"ml"`
// 	Mli              string `json:"mli"`
// 	Cmx              string `json:"cmx"`
// 	Cmxa             string `json:"cmxa"`
// 	Odata            string `json:"odata"`
// 	PhpInc           string `json:"php.inc"`
// 	Pipeline         string `json:"pipeline"`
// 	Pddl             string `json:"pddl"`
// 	Plan             string `json:"plan"`
// 	Happenings       string `json:"happenings"`
// 	Prisma           string `json:"prisma"`
// 	Pp               string `json:"pp"`
// 	Epp              string `json:"epp"`
// 	Purs             string `json:"purs"`
// 	SpecJsx          string `json:"spec.jsx"`
// 	TestJsx          string `json:"test.jsx"`
// 	Cjsx             string `json:"cjsx"`
// 	SpecTsx          string `json:"spec.tsx"`
// 	TestTsx          string `json:"test.tsx"`
// 	Re               string `json:"re"`
// 	Res              string `json:"res"`
// 	Resi             string `json:"resi"`
// 	R                string `json:"r"`
// 	Rmd              string `json:"rmd"`
// 	Erb              string `json:"erb"`
// 	ErbHTML          string `json:"erb.html"`
// 	HTMLErb          string `json:"html.erb"`
// 	Sass             string `json:"sass"`
// 	Springbeans      string `json:"springbeans"`
// 	Slim             string `json:"slim"`
// 	SmartyTpl        string `json:"smarty.tpl"`
// 	Tpl              string `json:"tpl"`
// 	Sbt              string `json:"sbt"`
// 	Scala            string `json:"scala"`
// 	Sol              string `json:"sol"`
// 	Styl             string `json:"styl"`
// 	Svelte           string `json:"svelte"`
// 	Soql             string `json:"soql"`
// 	Tf               string `json:"tf"`
// 	TfJSON           string `json:"tf.json"`
// 	Tfvars           string `json:"tfvars"`
// 	TfvarsJSON       string `json:"tfvars.json"`
// 	Dtx              string `json:"dtx"`
// 	Ins              string `json:"ins"`
// 	Toml             string `json:"toml"`
// 	Twig             string `json:"twig"`
// 	SpecTs           string `json:"spec.ts"`
// 	TestTs           string `json:"test.ts"`
// 	Vala             string `json:"vala"`
// 	Vapi             string `json:"vapi"`
// 	Component        string `json:"component"`
// 	Vue              string `json:"vue"`
// 	Wasm             string `json:"wasm"`
// 	Wat              string `json:"wat"`
// 	Pro              string `json:"pro"`
// 	Zig              string `json:"zig"`
// 	Jar              string `json:"jar"`
// 	Zip              string `json:"zip"`
// 	Wgt              string `json:"wgt"`
// 	Ai               string `json:"ai"`
// 	Psd              string `json:"psd"`
// 	Pdf              string `json:"pdf"`
// 	Eot              string `json:"eot"`
// 	Ttf              string `json:"ttf"`
// 	Woff             string `json:"woff"`
// 	Woff2            string `json:"woff2"`
// 	Avif             string `json:"avif"`
// 	Gif              string `json:"gif"`
// 	Jpg              string `json:"jpg"`
// 	Jpeg             string `json:"jpeg"`
// 	Png              string `json:"png"`
// 	Pxm              string `json:"pxm"`
// 	Svg              string `json:"svg"`
// 	Svgx             string `json:"svgx"`
// 	Tiff             string `json:"tiff"`
// 	Webp             string `json:"webp"`
// 	SublimeProject   string `json:"sublime-project"`
// 	SublimeWorkspace string `json:"sublime-workspace"`
// 	Mov              string `json:"mov"`
// 	Ogv              string `json:"ogv"`
// 	Webm             string `json:"webm"`
// 	Avi              string `json:"avi"`
// 	Mpg              string `json:"mpg"`
// 	Mp4              string `json:"mp4"`
// 	Mp3              string `json:"mp3"`
// 	Ogg              string `json:"ogg"`
// 	Wav              string `json:"wav"`
// 	Flac             string `json:"flac"`
// 	ThreeDs          string `json:"3ds"`
// 	ThreeDm          string `json:"3dm"`
// 	Stl              string `json:"stl"`
// 	Obj              string `json:"obj"`
// 	Dae              string `json:"dae"`
// 	Babelrc          string `json:"babelrc"`
// 	BabelrcJs        string `json:"babelrc.js"`
// 	BabelrcCjs       string `json:"babelrc.cjs"`
// 	Bazelrc          string `json:"bazelrc"`
// 	Bowerrc          string `json:"bowerrc"`
// 	Dockerignore     string `json:"dockerignore"`
// 	CodeclimateYml   string `json:"codeclimate.yml"`
// 	Eslintrc         string `json:"eslintrc"`
// 	EslintrcJs       string `json:"eslintrc.js"`
// 	EslintrcCjs      string `json:"eslintrc.cjs"`
// 	EslintrcYaml     string `json:"eslintrc.yaml"`
// 	EslintrcYml      string `json:"eslintrc.yml"`
// 	EslintrcJSON     string `json:"eslintrc.json"`
// 	Eslintignore     string `json:"eslintignore"`
// 	Firebaserc       string `json:"firebaserc"`
// 	GitlabCiYml      string `json:"gitlab-ci.yml"`
// 	Jshintrc         string `json:"jshintrc"`
// 	Jscsrc           string `json:"jscsrc"`
// 	Stylelintrc      string `json:"stylelintrc"`
// 	StylelintrcJSON  string `json:"stylelintrc.json"`
// 	StylelintrcYaml  string `json:"stylelintrc.yaml"`
// 	StylelintrcYml   string `json:"stylelintrc.yml"`
// 	StylelintrcJs    string `json:"stylelintrc.js"`
// 	Stylelintignore  string `json:"stylelintignore"`
// 	Direnv           string `json:"direnv"`
// 	Env              string `json:"env"`
// 	Static           string `json:"static"`
// 	Slugignore       string `json:"slugignore"`
// 	Tmp              string `json:"tmp"`
// 	Htaccess         string `json:"htaccess"`
// 	Key              string `json:"key"`
// 	Cert             string `json:"cert"`
// 	Cer              string `json:"cer"`
// 	Crt              string `json:"crt"`
// 	Pem              string `json:"pem"`
// 	DsStore          string `json:"ds_store"`
// }
// type FileNames struct {
// 	Mix                   string `json:"mix"`
// 	KarmaConfJs           string `json:"karma.conf.js"`
// 	KarmaConfCoffee       string `json:"karma.conf.coffee"`
// 	ReadmeMd              string `json:"readme.md"`
// 	ReadmeTxt             string `json:"readme.txt"`
// 	Readme                string `json:"readme"`
// 	ChangelogMd           string `json:"changelog.md"`
// 	ChangelogTxt          string `json:"changelog.txt"`
// 	Changelog             string `json:"changelog"`
// 	ChangesMd             string `json:"changes.md"`
// 	ChangesTxt            string `json:"changes.txt"`
// 	Changes               string `json:"changes"`
// 	VersionMd             string `json:"version.md"`
// 	VersionTxt            string `json:"version.txt"`
// 	Version               string `json:"version"`
// 	Mvnw                  string `json:"mvnw"`
// 	TsconfigJSON          string `json:"tsconfig.json"`
// 	SwaggerJSON           string `json:"swagger.json"`
// 	SwaggerYml            string `json:"swagger.yml"`
// 	SwaggerYaml           string `json:"swagger.yaml"`
// 	MimeTypes             string `json:"mime.types"`
// 	Jenkinsfile           string `json:"jenkinsfile"`
// 	BabelConfigJs         string `json:"babel.config.js"`
// 	BabelConfigJSON       string `json:"babel.config.json"`
// 	BabelConfigCjs        string `json:"babel.config.cjs"`
// 	Build                 string `json:"build"`
// 	BuildBazel            string `json:"build.bazel"`
// 	Workspace             string `json:"workspace"`
// 	WorkspaceBazel        string `json:"workspace.bazel"`
// 	BowerJSON             string `json:"bower.json"`
// 	DockerHealthcheck     string `json:"docker-healthcheck"`
// 	FirebaseJSON          string `json:"firebase.json"`
// 	Geckodriver           string `json:"geckodriver"`
// 	GruntfileJs           string `json:"gruntfile.js"`
// 	GruntfileBabelJs      string `json:"gruntfile.babel.js"`
// 	GruntfileCoffee       string `json:"gruntfile.coffee"`
// 	Gulpfile              string `json:"gulpfile"`
// 	GulpfileJs            string `json:"gulpfile.js"`
// 	IonicConfigJSON       string `json:"ionic.config.json"`
// 	IonicProject          string `json:"ionic.project"`
// 	PlatformioIni         string `json:"platformio.ini"`
// 	RollupConfigJs        string `json:"rollup.config.js"`
// 	SassLintYml           string `json:"sass-lint.yml"`
// 	StylelintConfigJs     string `json:"stylelint.config.js"`
// 	StylelintConfigCjs    string `json:"stylelint.config.cjs"`
// 	YarnClean             string `json:"yarn.clean"`
// 	YarnLock              string `json:"yarn.lock"`
// 	WebpackConfigJs       string `json:"webpack.config.js"`
// 	WebpackConfigCjs      string `json:"webpack.config.cjs"`
// 	WebpackConfigTs       string `json:"webpack.config.ts"`
// 	WebpackConfigBuildJs  string `json:"webpack.config.build.js"`
// 	WebpackConfigBuildCjs string `json:"webpack.config.build.cjs"`
// 	WebpackConfigBuildTs  string `json:"webpack.config.build.ts"`
// 	WebpackCommonJs       string `json:"webpack.common.js"`
// 	WebpackCommonCjs      string `json:"webpack.common.cjs"`
// 	WebpackCommonTs       string `json:"webpack.common.ts"`
// 	WebpackDevJs          string `json:"webpack.dev.js"`
// 	WebpackDevCjs         string `json:"webpack.dev.cjs"`
// 	WebpackDevTs          string `json:"webpack.dev.ts"`
// 	WebpackProdJs         string `json:"webpack.prod.js"`
// 	WebpackProdCjs        string `json:"webpack.prod.cjs"`
// 	WebpackProdTs         string `json:"webpack.prod.ts"`
// 	License               string `json:"license"`
// 	Licence               string `json:"licence"`
// 	LicenseTxt            string `json:"license.txt"`
// 	LicenceTxt            string `json:"licence.txt"`
// 	LicenseMd             string `json:"license.md"`
// 	LicenceMd             string `json:"licence.md"`
// 	Copying               string `json:"copying"`
// 	CopyingTxt            string `json:"copying.txt"`
// 	CopyingMd             string `json:"copying.md"`
// 	Compiling             string `json:"compiling"`
// 	CompilingTxt          string `json:"compiling.txt"`
// 	CompilingMd           string `json:"compiling.md"`
// 	Contributing          string `json:"contributing"`
// 	ContributingTxt       string `json:"contributing.txt"`
// 	ContributingMd        string `json:"contributing.md"`
// 	Qmakefile             string `json:"qmakefile"`
// 	Omakefile             string `json:"omakefile"`
// 	CmakelistsTxt         string `json:"cmakelists.txt"`
// 	Procfile              string `json:"procfile"`
// 	Todo                  string `json:"todo"`
// 	TodoTxt               string `json:"todo.txt"`
// 	TodoMd                string `json:"todo.md"`
// 	NpmDebugLog           string `json:"npm-debug.log"`
// }
// type LanguageIds struct {
// 	Bat             string `json:"bat"`
// 	Clojure         string `json:"clojure"`
// 	Coffeescript    string `json:"coffeescript"`
// 	Jsonc           string `json:"jsonc"`
// 	JSON            string `json:"json"`
// 	C               string `json:"c"`
// 	Cpp             string `json:"cpp"`
// 	CudaCpp         string `json:"cuda-cpp"`
// 	Csharp          string `json:"csharp"`
// 	CSS             string `json:"css"`
// 	Dart            string `json:"dart"`
// 	Dockerfile      string `json:"dockerfile"`
// 	Ignore          string `json:"ignore"`
// 	Fsharp          string `json:"fsharp"`
// 	GitCommit       string `json:"git-commit"`
// 	Go              string `json:"go"`
// 	Groovy          string `json:"groovy"`
// 	Handlebars      string `json:"handlebars"`
// 	HTML            string `json:"html"`
// 	Properties      string `json:"properties"`
// 	Java            string `json:"java"`
// 	Javascriptreact string `json:"javascriptreact"`
// 	Javascript      string `json:"javascript"`
// 	Julia           string `json:"julia"`
// 	Tex             string `json:"tex"`
// 	Latex           string `json:"latex"`
// 	Less            string `json:"less"`
// 	Lua             string `json:"lua"`
// 	Makefile        string `json:"makefile"`
// 	Markdown        string `json:"markdown"`
// 	ObjectiveC      string `json:"objective-c"`
// 	ObjectiveCpp    string `json:"objective-cpp"`
// 	Perl            string `json:"perl"`
// 	Php             string `json:"php"`
// 	Powershell      string `json:"powershell"`
// 	Jade            string `json:"jade"`
// 	Python          string `json:"python"`
// 	R               string `json:"r"`
// 	Razor           string `json:"razor"`
// 	Ruby            string `json:"ruby"`
// 	Rust            string `json:"rust"`
// 	Scss            string `json:"scss"`
// 	SearchResult    string `json:"search-result"`
// 	Shellscript     string `json:"shellscript"`
// 	SQL             string `json:"sql"`
// 	Swift           string `json:"swift"`
// 	Typescript      string `json:"typescript"`
// 	Typescriptreact string `json:"typescriptreact"`
// 	XML             string `json:"xml"`
// 	Dockercompose   string `json:"dockercompose"`
// 	Yaml            string `json:"yaml"`
// 	Argdown         string `json:"argdown"`
// 	Bicep           string `json:"bicep"`
// 	Elixir          string `json:"elixir"`
// 	Elm             string `json:"elm"`
// 	Erb             string `json:"erb"`
// 	GithubIssues    string `json:"github-issues"`
// 	Gradle          string `json:"gradle"`
// 	Godot           string `json:"godot"`
// 	Haml            string `json:"haml"`
// 	Haskell         string `json:"haskell"`
// 	Haxe            string `json:"haxe"`
// 	Jinja           string `json:"jinja"`
// 	Kotlin          string `json:"kotlin"`
// 	Mustache        string `json:"mustache"`
// 	Nunjucks        string `json:"nunjucks"`
// 	Ocaml           string `json:"ocaml"`
// 	Rescript        string `json:"rescript"`
// 	Sass            string `json:"sass"`
// 	Stylus          string `json:"stylus"`
// 	Terraform       string `json:"terraform"`
// 	Todo            string `json:"todo"`
// 	Vala            string `json:"vala"`
// 	Vue             string `json:"vue"`
// 	Jsonl           string `json:"jsonl"`
// 	Postcss         string `json:"postcss"`
// 	DjangoHTML      string `json:"django-html"`
// 	Blade           string `json:"blade"`
// }
// type LanguageIds struct {
// 	Bat             string `json:"bat"`
// 	Clojure         string `json:"clojure"`
// 	Coffeescript    string `json:"coffeescript"`
// 	Jsonc           string `json:"jsonc"`
// 	JSON            string `json:"json"`
// 	C               string `json:"c"`
// 	Cpp             string `json:"cpp"`
// 	CudaCpp         string `json:"cuda-cpp"`
// 	Csharp          string `json:"csharp"`
// 	CSS             string `json:"css"`
// 	Dart            string `json:"dart"`
// 	Dockerfile      string `json:"dockerfile"`
// 	Ignore          string `json:"ignore"`
// 	Fsharp          string `json:"fsharp"`
// 	GitCommit       string `json:"git-commit"`
// 	Go              string `json:"go"`
// 	Groovy          string `json:"groovy"`
// 	Handlebars      string `json:"handlebars"`
// 	HTML            string `json:"html"`
// 	Properties      string `json:"properties"`
// 	Java            string `json:"java"`
// 	Javascriptreact string `json:"javascriptreact"`
// 	Javascript      string `json:"javascript"`
// 	Julia           string `json:"julia"`
// 	Tex             string `json:"tex"`
// 	Latex           string `json:"latex"`
// 	Less            string `json:"less"`
// 	Lua             string `json:"lua"`
// 	Makefile        string `json:"makefile"`
// 	Markdown        string `json:"markdown"`
// 	ObjectiveC      string `json:"objective-c"`
// 	ObjectiveCpp    string `json:"objective-cpp"`
// 	Perl            string `json:"perl"`
// 	Php             string `json:"php"`
// 	Powershell      string `json:"powershell"`
// 	Jade            string `json:"jade"`
// 	Python          string `json:"python"`
// 	R               string `json:"r"`
// 	Razor           string `json:"razor"`
// 	Ruby            string `json:"ruby"`
// 	Rust            string `json:"rust"`
// 	Scss            string `json:"scss"`
// 	SearchResult    string `json:"search-result"`
// 	Shellscript     string `json:"shellscript"`
// 	SQL             string `json:"sql"`
// 	Swift           string `json:"swift"`
// 	Typescript      string `json:"typescript"`
// 	Typescriptreact string `json:"typescriptreact"`
// 	XML             string `json:"xml"`
// 	Dockercompose   string `json:"dockercompose"`
// 	Yaml            string `json:"yaml"`
// 	Argdown         string `json:"argdown"`
// 	Bicep           string `json:"bicep"`
// 	Elixir          string `json:"elixir"`
// 	Elm             string `json:"elm"`
// 	Erb             string `json:"erb"`
// 	GithubIssues    string `json:"github-issues"`
// 	Gradle          string `json:"gradle"`
// 	Godot           string `json:"godot"`
// 	Haml            string `json:"haml"`
// 	Haskell         string `json:"haskell"`
// 	Haxe            string `json:"haxe"`
// 	Jinja           string `json:"jinja"`
// 	Kotlin          string `json:"kotlin"`
// 	Mustache        string `json:"mustache"`
// 	Nunjucks        string `json:"nunjucks"`
// 	Ocaml           string `json:"ocaml"`
// 	Rescript        string `json:"rescript"`
// 	Sass            string `json:"sass"`
// 	Stylus          string `json:"stylus"`
// 	Terraform       string `json:"terraform"`
// 	Vala            string `json:"vala"`
// 	Vue             string `json:"vue"`
// 	Jsonl           string `json:"jsonl"`
// 	Postcss         string `json:"postcss"`
// 	DjangoHTML      string `json:"django-html"`
// 	Blade           string `json:"blade"`
// }
// type FileNames struct {
// 	Mix                   string `json:"mix"`
// 	KarmaConfJs           string `json:"karma.conf.js"`
// 	KarmaConfCoffee       string `json:"karma.conf.coffee"`
// 	ReadmeMd              string `json:"readme.md"`
// 	ReadmeTxt             string `json:"readme.txt"`
// 	Readme                string `json:"readme"`
// 	ChangelogMd           string `json:"changelog.md"`
// 	ChangelogTxt          string `json:"changelog.txt"`
// 	Changelog             string `json:"changelog"`
// 	ChangesMd             string `json:"changes.md"`
// 	ChangesTxt            string `json:"changes.txt"`
// 	Changes               string `json:"changes"`
// 	VersionMd             string `json:"version.md"`
// 	VersionTxt            string `json:"version.txt"`
// 	Version               string `json:"version"`
// 	Mvnw                  string `json:"mvnw"`
// 	TsconfigJSON          string `json:"tsconfig.json"`
// 	SwaggerJSON           string `json:"swagger.json"`
// 	SwaggerYml            string `json:"swagger.yml"`
// 	SwaggerYaml           string `json:"swagger.yaml"`
// 	MimeTypes             string `json:"mime.types"`
// 	Jenkinsfile           string `json:"jenkinsfile"`
// 	BabelConfigJs         string `json:"babel.config.js"`
// 	BabelConfigJSON       string `json:"babel.config.json"`
// 	BabelConfigCjs        string `json:"babel.config.cjs"`
// 	Build                 string `json:"build"`
// 	BuildBazel            string `json:"build.bazel"`
// 	Workspace             string `json:"workspace"`
// 	WorkspaceBazel        string `json:"workspace.bazel"`
// 	BowerJSON             string `json:"bower.json"`
// 	DockerHealthcheck     string `json:"docker-healthcheck"`
// 	FirebaseJSON          string `json:"firebase.json"`
// 	Geckodriver           string `json:"geckodriver"`
// 	GruntfileJs           string `json:"gruntfile.js"`
// 	GruntfileBabelJs      string `json:"gruntfile.babel.js"`
// 	GruntfileCoffee       string `json:"gruntfile.coffee"`
// 	Gulpfile              string `json:"gulpfile"`
// 	GulpfileJs            string `json:"gulpfile.js"`
// 	IonicConfigJSON       string `json:"ionic.config.json"`
// 	IonicProject          string `json:"ionic.project"`
// 	PlatformioIni         string `json:"platformio.ini"`
// 	RollupConfigJs        string `json:"rollup.config.js"`
// 	SassLintYml           string `json:"sass-lint.yml"`
// 	StylelintConfigJs     string `json:"stylelint.config.js"`
// 	StylelintConfigCjs    string `json:"stylelint.config.cjs"`
// 	YarnClean             string `json:"yarn.clean"`
// 	YarnLock              string `json:"yarn.lock"`
// 	WebpackConfigJs       string `json:"webpack.config.js"`
// 	WebpackConfigCjs      string `json:"webpack.config.cjs"`
// 	WebpackConfigTs       string `json:"webpack.config.ts"`
// 	WebpackConfigBuildJs  string `json:"webpack.config.build.js"`
// 	WebpackConfigBuildCjs string `json:"webpack.config.build.cjs"`
// 	WebpackConfigBuildTs  string `json:"webpack.config.build.ts"`
// 	WebpackCommonJs       string `json:"webpack.common.js"`
// 	WebpackCommonCjs      string `json:"webpack.common.cjs"`
// 	WebpackCommonTs       string `json:"webpack.common.ts"`
// 	WebpackDevJs          string `json:"webpack.dev.js"`
// 	WebpackDevCjs         string `json:"webpack.dev.cjs"`
// 	WebpackDevTs          string `json:"webpack.dev.ts"`
// 	WebpackProdJs         string `json:"webpack.prod.js"`
// 	WebpackProdCjs        string `json:"webpack.prod.cjs"`
// 	WebpackProdTs         string `json:"webpack.prod.ts"`
// 	License               string `json:"license"`
// 	Licence               string `json:"licence"`
// 	LicenseTxt            string `json:"license.txt"`
// 	LicenceTxt            string `json:"licence.txt"`
// 	LicenseMd             string `json:"license.md"`
// 	LicenceMd             string `json:"licence.md"`
// 	Copying               string `json:"copying"`
// 	CopyingTxt            string `json:"copying.txt"`
// 	CopyingMd             string `json:"copying.md"`
// 	Compiling             string `json:"compiling"`
// 	CompilingTxt          string `json:"compiling.txt"`
// 	CompilingMd           string `json:"compiling.md"`
// 	Contributing          string `json:"contributing"`
// 	ContributingTxt       string `json:"contributing.txt"`
// 	ContributingMd        string `json:"contributing.md"`
// 	Qmakefile             string `json:"qmakefile"`
// 	Omakefile             string `json:"omakefile"`
// 	CmakelistsTxt         string `json:"cmakelists.txt"`
// 	Procfile              string `json:"procfile"`
// 	NpmDebugLog           string `json:"npm-debug.log"`
// }
// type Light struct {
// 	File           string         `json:"file"`
// 	FileExtensions FileExtensions `json:"fileExtensions"`
// 	LanguageIds    LanguageIds    `json:"languageIds"`
// 	FileNames      FileNames      `json:"fileNames"`
// }
